version: '2'
services:

  web:
    build: .
    container_name: jumio_django
    volumes:
      - .:/django

  nginx:
    image: nginx
    container_name: jumio_nginx
    ports:
      - "9000:8000"
    volumes:
      - .:/django
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
